config/routes.rb
Rsvp::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"} 

	devise_scope :user do
  	match "/registrations/list_invites" => "registrations#list"
  	match "/registrations/logon" => "registrations#create"
	end
  devise_for :admins

  resources :addresses

  resources :invitations

	match '/invitations/send_save_the_date', :to => 'invitations#send_save_the_date', :as => 'send_save_the_date'
	match '/registrations/list_invites', :to => 'registrations#list', :as => 'list_invites'
	match '/registrations/logon', :to => 'registrations#create', :as => 'login_to_invite'

	match '/registry', :to => 'home#registry', :as => 'registry'
	match '/itinerary', :to => 'home#itinerary', :as => 'itinerary'
	match '/accommodations', :to => 'home#accommodations', :as => 'accommodations'
	match '/venue', :to => 'home#venue', :as => 'venue'

	match '/dashboard', :to => 'dashboard#main', :as => 'dashboard'
	match '/admin_index', :to => 'invitations#admin_index', :as => 'admin_index'
	match '/thankyou', :to => 'invitations#thankyou', :as => 'thankyou'
	match '/thankyou_gift', :to => 'home#thankyou'

  root :to => "home#index"
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	has_one :address
	belongs_to :admin
	accepts_nested_attributes_for :address
	before_validation :generate_code
	validates_uniqueness_of :invite_code
	validates_presence_of :invite_code, :first_names, :last_name, :spots, :rsvp_number	
	default_scope :order => "admin_id DESC"

	def self.get_reports
		reports = Hash.new
		reports['spots'] = Invitation.sum(:spots)
		reports['rsvp'] = Invitation.sum(:rsvp_number)
		reports['owner_hash'] = Invitation.owner_hash

		return reports
	end

	
	def self.owner_hash
		unique_owners = Admin.all
		owner_hash = Hash.new
		unless unique_owners.blank?
			unique_owners.each do |unique_owner|
				owner_hash[unique_owner.email] = Invitation.where(:admin_id => unique_owner.id).sum(:spots)
			end
		end

		return owner_hash
	end

	def self.search(search)
	  if search
	   	where('last_name LIKE ?', "%#{search}%")
	  else
	    scoped
  	end
	end


	def set_save_the_date(is_sent)
		self.save_the_date_sent = is_sent
	end

	def set_invitation(is_sent)
		self.invitation_sent = is_sent
	end

	def generate_code
		if self.invite_code.blank?
			self.invite_code = 'l' + rand(9).to_s + 'o' + rand(9).to_s + 'v' + rand(9).to_s + 'e' 
		end
	end

	def change_address(params)
		if self.address.blank?
			self.build_address
		end

		self.address.attributes = params
	end

	def make_errors
		errors = ""
		self.errors.full_messages.each do |msg|
			errors = errors + ' - ' + msg
		end

		return errors
	end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
	helper_method :sort_column, :sort_direction
  # GET /invitations
  # GET /invitations.json
  def index
		if admin_signed_in?
			redirect_to admin_index_path
			return
		end

		if session[:is_authenticated] 
			@invitation = Invitation.find(session[:invitation_id])
			
			if @invitation.address.blank?
				@invitation.build_address
			end
		else
			session[:is_authenticated] = false
			session[:invitation_id] = nil
			redirect_to new_user_registration_path	
		end
  end
		
	def admin_index
		if !admin_signed_in?
			redirect_to root_path
			return
		end

		@invitations = Invitation.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 100, :page => params[:page])
		@new_invitation = Invitation.new
		@reports = Invitation.get_reports

	end
	
  # GET /invitations/1
  # GET /invitations/1.json
  def show
    @invitation = Invitation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invitation }
    end
  end

  # GET /invitations/new
  # GET /invitations/new.json
  def new
    @invitation = Invitation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invitation }
    end
  end

  # GET /invitations/1/edit
  def edit
		if !admin_signed_in?
			redirect_to root_path
			return
		end

    @invitation = Invitation.find(params[:id])
  end

  # POST /invitations
  # POST /invitations.json
  def create
		if !admin_signed_in?
			redirect_to root_path
			return
		end

    @invitation = Invitation.new(params[:invitation])
		@invitation.admin_id = current_admin.id

    if @invitation.save
     	redirect_to admin_index_path, notice: 'Invitation was successfully created.' 
   	else
    	redirect_to admin_index_path, notice: @invitation.make_errors 
   	end
  end

  # PUT /invitations/1
  # PUT /invitations/1.json
  def update
    @invitation = Invitation.find(params[:id])

		if admin_signed_in?
			@invitation.attributes = params[:invitation] 

			unless params[:address].blank? 
				@invitation.change_address(params[:address])
			end
			
      if @invitation.save
       	redirect_to @invitation, notice: "Invitation successfully updated."
     	else
       	render 'edit'
     	end
		else
			session[:invitation_id] = @invitation.id 
			@invitation.attributes = params[:invitation] 
			@invitation.rsvp_number = params[:rsvp_number]
			@invitation.change_address(params[:address])

     	if @invitation.save
				session[:invitation_id] = nil
				session[:is_authenticated] = nil
       	redirect_to thankyou_path
     	else
       	render :index
      end
		end
  end
	
	def thankyou
	end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
		if !admin_signed_in?
			redirect_to  
			return
		end

    @invitation = Invitation.find(params[:id])
    @invitation.destroy

    respond_to do |format|
      format.html { redirect_to invitations_url }
      format.json { head :no_content }
    end
  end

	def send_save_the_date
		if !admin_signed_in?
			redirect_to root_path
			return
		end
		
		invitation = Invitation.find(params[:id])
		
		if invitation.spots > 0
			begin
				Mailer.save_the_date(invitation).deliver!

				invitation.save_the_date_sent = true
				invitation.save
				render :text => "Save the Date email sent!"
			rescue
				render :text => "There was an issue sending this Save the Date."
			end
		else
			render :text => "This invitaiton has 0 allowed guests.  No Save the Date sent."
		end
	end

	private

	def sort_column
		params[:sort] || "first_names"
		%w[first_names last_name spots rsvp_number admin_id].include?(params[:sort]) ? params[:sort] : "first_names"
	end

	def sort_direction
		%w[as desc].include?(params[:direction]) ? params[:direction] : "asc"
	end

	end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_admin_list.html.erb
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>

	<% @invitations.each do |inv| %>
		<div class="row">
			<div class="span2" >
				<div class="right" >
					<div style="width: 100%; height: 25px;"></div>
					<% if inv.email.blank? || inv.save_the_date_sent == false %>
						<table class="red_letters">
					<% else %>
						<table>
					<% end %>
						<tr/>
							<td><%= "#{inv.save_the_date_sent}" %></td>
							<td> | </td>
							<td><%= link_to 'show', inv %></td>
							<%# if inv.admin_id == current_admin.id %>
							<% if true %>
								<td> | </td>
    						<td><%= link_to 'edit', edit_invitation_path(inv) %></td>
								<td> | </td>
    						<td>
									<%= link_to 'destroy', inv, confirm: 'are you sure?', method: :delete %>
								</td>
							<% end %>
						</tr>
					</table>
				</div>
  		</div>

			<div class="span2">
   			<%= sortable( "first_names", "First names") %>
   			<%= text_field_tag :first_names, inv.first_names, :readonly => true %>
  		</div>
			<div class="span2">
    		<%= sortable("last_name", "Last name") %>
    		<%= text_field_tag :last_name, inv.last_name, :readonly => true %>
			</div>
			<div class="span2">
   			<%= label_tag :invite_code %>
   			<%= text_field_tag :invite_code, inv.invite_code, :readonly => true %>
  		</div>
			<div class="span2">
				<table>
					<tr>
						<td>&nbsp;</td>
   					<td><%= sortable("spots", "Spots") %></td>
						<td>&nbsp;</td>
						<td><%= sortable("rsvp_number", "Rsvp") %></td>
						<td>&nbsp;</td>
						<td><%= sortable("admin_id", "Owner") %></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
   					<td><%= number_field_tag :spots, inv.spots, :readonly => true %></td>
						<td>&nbsp;</td>
   					<td><%= number_field_tag :rsvp_number, inv.rsvp_number, :readonly => true %></td>
						<td>&nbsp;</td>
						<td><%= text_field_tag :admin, inv.admin.email.split('@')[0], :readonly => true %></td>
					</tr>
				</table>
  		</div>
		</div>
	<% end %>

	<div class="row">
		<div class="span12">
			<div class="center2 kill">
				<%= will_paginate @invitations %>
			</div>
		</div>
	</div>

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
	<div class="row">
		<div class="span2">&nbsp;</div>
		<div class="span8">
				<% if @invitation.errors.any? %>
    			<div id="error_explanation">
						<h2>please fix the following:</h2>
      			<ul>
      				<% @invitation.errors.full_messages.each do |msg| %>
        				<li><%= msg %></li>
      				<% end %>
      			</ul>
    			</div>
  			<% end %>
		</div>
	</div>

  	<div class="row">
		<div class="span2">&nbsp;</div>
		<div class="span8">
			<p class="message">
    		<%= @invitation.login_message %>  
			</p>
		</div>
	</div>

<div class="row">
	<div class="span4">
  	<div class="right">
			<div class="center2">
    		<%= f.label :first_names %>
    		<%= f.text_field :first_names, :readonly => true %>
			</div>
  	</div>
	</div>

	<div class="span4">
  	<div class="center2">
    	<%= f.label :last_name %>
    	<%= f.text_field :last_name, :readonly => true %>
  	</div>
	</div>

	<div class="span4">
		<div class="left">
			<div class="center2">
    		<%= f.label :invite_code %>
    		<%= f.text_field :invite_code, :readonly => true %>
			</div>
  	</div>
	</div>
</div> <!-- end row one -->

<%= f.fields_for :address do |a| %>
	<div class="row">
		<div class="span4">
			<div class="right">
				<div class="center2">
    			<%= a.label :street %>
    			<%= a.text_field :street %>
  			</div>
			</div>
		</div>

		<div class="span4">
  		<div class="center2">
    		<%= a.label :city %>
    		<%= a.text_field :city %>
  		</div>
		</div>

		<div class="span4">
  		<div class="left">
				<div class="center2">
					<%= a.label :state %>
    			<%= a.text_field :state %>
  			</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="span4">
			<div class="right">
				<div class="center2">
					<%= a.label :zip %>
    			<%= a.text_field :zip %>
  			</div>
			</div>
		</div>

		<div class="span4">
  		<div class="center2">
				<%= a.label :cell %>
    		<%= a.telephone_field :cell %>
  		</div>
		</div>

		<div class="span4">
  		<div class="left">
				<div class="center2">
					<%= a.label :email %>
    			<%= a.email_field :email %>
  			</div>
			</div>
		</div>
	</div>	
<% end %>

	<div class="row">
		<div class="span2">&nbsp;</div>
		<div class="span8">
			<div class="center2">
				<br/>
				<fieldset>
					<legend>number attending</legend>
					<% none_selection = "I can't go" %>
					<% if @invitation.spots > 1 %>
						<% none_selection = "we can't go" %>
					<% end %>
				  <%  (0..@invitation.spots).each do |spot| %>
						<%= radio_button_tag 'rsvp_number', spot, @invitation.rsvp_number == spot %>
						<% if spot == 0 %>
							<%= none_selection %>
						<% elsif spot == 1 %>
							<%= "#{spot} person is attending"  %>
						<% else %>
							<%= "#{spot} people are attending"  %>
						<% end %>
						<% unless @invitation.spots == spot %>
							<span>&nbsp;&nbsp;|&nbsp;&nbsp;</span>
						<% end %>
					<% end %>
				</fieldset>
			</div>
		</div>	
	</div>

	<div class="row">
		<div class="span2">&nbsp;</div>
		<div class="span8">
			<div class="center2">
				<br/>
				<br/>
				<fieldset>
					<legend>leave comments</legend>
    			<%= f.text_area :feedback, :rows => 2, :cols => 50 %>
				</fieldset>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="span2">&nbsp;</div>
		<div class="span8">
			<div class="center2">
				<br/>
				<br/>
  			<div class="actions">
					<%= f.submit %><br/>
					<span><i>you can revise/add to your contact information at any time - when you're done, just click update</i></span>
				</div>
			</div>
		</div>
	</div>

      </div>
<% end %>

app/views/invitations/admin_index.html.erb
<div class="row">
	<div class="span12">
		<header class="gen_title"> 	
			<h2 class="center-align">dashboard</h2>
			<p class="notice"><%= notice %></p>
		</header>
	</div>
</div>

<div class="row">
	<div class="span12">
		<div class="center2">
			<span><b> number invited :</b> <%= @reports['spots'] %></span>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
			<span><b> number rsvped :</b> <%= @reports['rsvp'] %></span>
		</div>
	</div>
</div>

<div class="row">
	<div class="span12">
		<br/><br/>
		<fieldset class="gen_title"> 	
			<legend>owners</h2>
		</fieldset>
	</div>
</div>

<div class="row">
	<% @reports['owner_hash'].each do |email, count| %>
		<div class="span3">
			<span><%= "#{email} : #{count}" %></span>
		</div>
	<% end %>
</div>

<div id="list">
	<div class="row">
		<div class="span12">
			<br/><br/>
			<fieldset class="gen_title"> 	
				<legend>add new</h2>
			</fieldset>
		</div>
	</div>

	<%= form_for @new_invitation do |f| %>
		<div class="row">
			<div class="span2" >
				<div class="right" >
					<div style="width: 100%; height: 25px;"></div>
					<table><tr/>
					</tr></table>
				</div>
  		</div>

			<div class="span2">
   			<%= f.label :first_names %>
   			<%= f.text_field :first_names %>
  		</div>
			<div class="span2">
    		<%= f.label :last_name %>
    		<%= f.text_field :last_name %>
			</div>
			<div class="span2">
   			<%= f.label :invite_code %>
   			<%= f.text_field :invite_code, :readonly => true %>
  		</div>
			<div class="span2">
				<table>
					<tr>
						<td>&nbsp;</td>
   					<td><%= f.label :spots %></td>
						<td>&nbsp;</td>
						<td><%= f.label :rsvp_number, 'Rsvp' %></td>
						<td>&nbsp;</td>
						<td></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
   					<td><%= f.number_field :spots %></td>
						<td>&nbsp;</td>
   					<td><%= f.number_field :rsvp_number, :readonly => true %></td>
						<td>&nbsp;</td>
						<td style="vertical-align: middle;">
							<%= f.submit 'Submit' %></td>
						</td>
					</tr>
				</table>
  		</div>
		</div>
	<% end %>

	<div class="row">
		<div class="span12">
			<br/><br/>
			<fieldset class="gen_title"> 	
				<legend>current roster</h2>
			</fieldset>
		</div>
	</div>

	<%= form_tag admin_index_path, :method => 'get', :id => "invitations_search" do %>
		<div class="row">
			<div class="span3 offset7">
				<div class="right">
					<br/>
					<%= text_field_tag :search, params[:search] %>
					<%= submit_tag "Search", :last_name => nil %>	
					&nbsp;
				</div>
			</div>
		</div>
		<div id="invitations">
			<%= render 'admin_list' %>
		</div>
	<% end %>

			
</div> <!-- end of list -->

app/views/invitations/admin_index.js.erb
$("#invitations").html("<%= escape_javascript(render 'admin_list') %>");

app/views/invitations/edit.html.erb
<div class="row">
	<div class="span12">
		<header class="gen_title"> 	
			<h2 class="center-align">edit invitation</h2>
			<p class="notice"><%= notice %></p>
		</header>
	</div>
</div>
<div class="show">
<%= form_for(@invitation) do |f| %>
	<div class="row">
		<div class="span2">&nbsp;</div>
		<div class="span8">
				<% if @invitation.errors.any? %>
    			<div id="error_explanation">
						<h2>please fix the following:</h2>
      			<ul>
      				<% @invitation.errors.full_messages.each do |msg| %>
        				<li><%= msg %></li>
      				<% end %>
      			</ul>
    			</div>
  			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="span4">
  		<div class="right">
				<div class="center2">
    			<%= f.label :first_names %>
    			<%= f.text_field :first_names %>
				</div>
  		</div>
		</div>
		<div class="span4">
  		<div class="center2">
    		<%= f.label :last_name %>
    		<%= f.text_field :last_name %>
  		</div>
		</div>
		<div class="span4">
			<div class="left">
				<div class="center2">
    			<%= f.label :invite_code %>
    			<%= f.text_field :invite_code, :readonly => true %>
				</div>
  		</div>
		</div>
	</div> <!-- end row one -->

	<div id="address_div">
	</div>

	<%= f.fields_for :address do |a| %>
		<div class="row">
			<div class="span4">
				<div class="right">
					<div class="center2">
    				<%= a.label :street %>
    				<%= a.text_field :street %>
  				</div>
				</div>
			</div>
			<div class="span4">
  			<div class="center2">
    			<%= a.label :city %>
    			<%= a.text_field :city %>
  			</div>
			</div>

			<div class="span4">
  			<div class="left">
					<div class="center2">
						<%= a.label :state %>
    				<%= a.text_field :state %>
  				</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="span4">
				<div class="right">
					<div class="center2">
						<%= a.label :zip %>
    				<%= a.text_field :zip %>
  				</div>
				</div>
			</div>
			<div class="span4">
  			<div class="center2">
					<%= a.label :cell %>
    			<%= a.telephone_field :cell %>
  			</div>
			</div>
			<div class="span4">
  			<div class="left">
					<div class="center2">
						<%= a.label :email, "Contact Email" %>
    				<%= a.email_field :email, :read_only => true %>
  				</div>
				</div>
			</div>
		</div>	
	<% end %>

	<div class="row">
		<div class="span4">
			<div class="right">
				<div class="center2">
					<%= f.label :spots, 'Spots allowed' %>
    			<%= f.number_field :spots %>
  			</div>
			</div>
		</div>	
		<div class="span4">
			<div class="center2">
				<%= f.label :rsvp_number, 'Rsvp number' %>
    		<%= f.number_field :rsvp_number, :readonly => true %>
			</div>
		</div>
		<div class="span4">
			<div class="left">
				<div class="center2">
					<%= f.label :gift %>
    			<%= f.text_field :gift %>
  			</div>
			</div>
		</div>	
	</div>

	<div class="row">
		<div class="span4 offset4">
			<div class="center2">
				<%= f.label :email, "Invitation Email" %>
    		<%= f.email_field :email %>
		</div>
	</div>
	<% if @invitation.address.blank? %>
		<div class=row>
			<div class="span2 offset5">
				<div class="center2">
					<span>Add address?&nbsp;</span>
					<%= check_box_tag :add_address, @invitation.address.blank? %>
				</div>
			</div>
		</div>
	<% end %>


	<div class="row">
		<div class="span5 offset1">
			<div class="right">
				<%= f.label :login_message %>
    		<%= f.text_area :login_message %>
			</div>
		</div>
		<div class="span5">
			<div class="left">
				<%= f.label :feedback %>
    		<%= f.text_area :feedback , :readonly => true %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="span2">&nbsp;</div>
		<div class="span8">
			<div class="center2">
    		<span>Thank you note sent?</span>&nbsp;&nbsp;<%= f.check_box :thank_you %>

			</div>
		</div>
	</div>

	<div class="row">
		<div class="span2">&nbsp;</div>
		<div class="span8">
			<div class="center2">
				<br/>
				<%= f.submit %>
				<br/>
				<%= link_to 'Show', @invitation %> |
				<%= link_to 'Back', invitations_path %>
			</div>
		</div>
	</div>

      </div>
<% end %>
</div>

app/views/invitations/edit.js.erb
$("#address_div").html("<%= escape_javascript(render 'addresses/admin_address', :locals => {:address => Address.new}) %>");

app/views/invitations/index.html.erb
<div class="row">
	<div class="span12">
		<header class="gen_title"> 	
			<h2 class="center-align">verify contact information</h2>
			<p class="notice"><%= notice %></p>
		</header>
	</div>
</div>

<%= render 'invitations/form' %>

<script type='text/javascript'>
	$(document).ready(function () {
		$('#rsvp').addClass('active');	
	});
</script>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<div class="row">
	<div class="span12">
		<header class="gen_title"> 	
			<h2 class="center-align">show invitation</h2>
			<p class="notice"><%= notice %></p>
		</header>
	</div>
</div>
<div class="show">
<%= form_for(@invitation) do |f| %>
	<div class="row">
		<div class="span2">&nbsp;</div>
		<div class="span8">
				<% if @invitation.errors.any? %>
    			<div id="error_explanation">
						<h2>please fix the following:</h2>
      			<ul>
      				<% @invitation.errors.full_messages.each do |msg| %>
        				<li><%= msg %></li>
      				<% end %>
      			</ul>
    			</div>
  			<% end %>
		</div>
	</div>

<div class="row">
	<div class="span4">
  	<div class="right">
			<div class="center2">
    		<%= f.label :first_names %>
    		<%= f.text_field :first_names, :readonly => true %>
			</div>
  	</div>
	</div>

	<div class="span4">
  	<div class="center2">
    	<%= f.label :last_name %>
    	<%= f.text_field :last_name, :readonly => true %>
  	</div>
	</div>

	<div class="span4">
		<div class="left">
			<div class="center2">
    		<%= f.label :invite_code %>
    		<%= f.text_field :invite_code, :readonly => true %>
			</div>
  	</div>
	</div>
</div> <!-- end row one -->

<%= f.fields_for :address do |a| %>
	<div class="row">
		<div class="span4">
			<div class="right">
				<div class="center2">
    			<%= a.label :street %>
    			<%= a.text_field :street , :readonly => true %>
  			</div>
			</div>
		</div>

		<div class="span4">
  		<div class="center2">
    		<%= a.label :city %>
    		<%= a.text_field :city , :readonly => true %>
  		</div>
		</div>

		<div class="span4">
  		<div class="left">
				<div class="center2">
					<%= a.label :state %>
    			<%= a.text_field :state , :readonly => true %>
  			</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="span4">
			<div class="right">
				<div class="center2">
					<%= a.label :zip %>
    			<%= a.text_field :zip , :readonly => true %>
  			</div>
			</div>
		</div>

		<div class="span4">
  		<div class="center2">
				<%= a.label :cell %>
    		<%= a.telephone_field :cell , :readonly => true %>
  		</div>
		</div>

		<div class="span4">
  		<div class="left">
				<div class="center2">
					<%= a.label :email %>
    			<%= a.email_field :email , :readonly => true %>
  			</div>
			</div>
		</div>
	</div>	
<% end %>

	<div class="row">
		<div class="span4">
			<div class="right">
				<div class="center2">
					<%= f.label :spots, 'Spots allowed' %>
    			<%= f.number_field :spots , :readonly => true %>
  			</div>
			</div>
		</div>	
		<div class="span4">
			<div class="center2">
				<%= f.label :rsvp_number, 'Rsvp number' %>
    		<%= f.number_field :rsvp_number , :readonly => true %>
			</div>
		</div>
		<div class="span4">
			<div class="left">
				<div class="center2">
					<%= f.label :gift %>
    			<%= f.text_field :gift , :readonly => true %>
  			</div>
			</div>
		</div>	
	</div>

	<div class="row">
		<div class="span4 offset4">
			<div class="center2">
				<%= f.label :email, "Invitation Email" %>
    		<%= f.email_field :email, :readonly => true %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="span5 offset1">
			<div class="right">
				<%= f.label :login_message %>
    		<%= f.text_area :login_message, :readonly => true %>
			</div>
		</div>
		<div class="span5">
			<div class="left">
				<%= f.label :feedback %>
    		<%= f.text_area :feedback , :readonly => true %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="span4">
			<div class="right">
				<div class="center2">
    			<span>Thank you note sent?</span>&nbsp;&nbsp;<%= f.check_box :thank_you , :readonly => true %>
  			</div>
			</div>
		</div>

		<div class="span4">
  		<div class="center2">
    			<span>Save the date sent?</span>&nbsp;&nbsp;<%= f.check_box :save_the_date_sent , :readonly => true %>
  		</div>
		</div>

		<div class="span4">
  		<div class="left">
				<div class="center2">
    			<span>Invitation sent?</span>&nbsp;&nbsp;<%= f.check_box :invitation_sent , :readonly => true %>
  			</div>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="span2">&nbsp;</div>
	</div>

	<div class="row">
		<div class="span8 offset2">
			<div class="center2">
				<button type="button" value=<%= @invitation.id%> id="send_save_the_date">Send "Save the Date"</button>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="span8 offset2">
			<div class="center2">
				<div id="result"></div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="span2">&nbsp;</div>
		<div class="span8">
			<div class="center2">
				<br/>
				<br/>
				<% if @invitation.admin_id == current_admin.id %>
					<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
				<% end %>
				<%= link_to 'Back', invitations_path %>
			</div>
		</div>
	</div>

      </div>
<% end %>
</div>

<script type="text/javascript">
	$('#send_save_the_date').click(function() {
		 $.ajax({url: '<%= send_save_the_date_path(:id => @invitation.id.to_s) %>',
				type: "POST",
        dataType: 'html',
				success: function(data) { $('#result').html(data); } });


	});
</script>

app/views/invitations/thankyou.html.erb
<div class="row">
	<div class="span12">
		<header class="gen_title"> 	
			<h2 class="center-align">thank you for rsvping</h2>
			<p class="notice"><%= notice %></p>
		</header>
	</div>
</div>