config/routes.rb
Rsvp::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"} 

	devise_scope :user do
  	match "/registrations/list_invites" => "registrations#list"
  	match "/registrations/logon" => "registrations#create"
	end
  devise_for :admins

  resources :addresses

  resources :invitations

	match '/invitations/send_save_the_date', :to => 'invitations#send_save_the_date', :as => 'send_save_the_date'
	match '/registrations/list_invites', :to => 'registrations#list', :as => 'list_invites'
	match '/registrations/logon', :to => 'registrations#create', :as => 'login_to_invite'

	match '/registry', :to => 'home#registry', :as => 'registry'
	match '/itinerary', :to => 'home#itinerary', :as => 'itinerary'
	match '/accommodations', :to => 'home#accommodations', :as => 'accommodations'
	match '/venue', :to => 'home#venue', :as => 'venue'

	match '/dashboard', :to => 'dashboard#main', :as => 'dashboard'
	match '/admin_index', :to => 'invitations#admin_index', :as => 'admin_index'
	match '/thankyou', :to => 'invitations#thankyou', :as => 'thankyou'
	match '/thankyou_gift', :to => 'home#thankyou'

  root :to => "home#index"
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_admin_address.html.erb
<%= fields_for :address do |a| %>
		<div class="row">
			<div class="span4">
				<div class="right">
					<div class="center2">
    				<%= a.label :street %>
    				<%= a.text_field :street %>
  				</div>
				</div>
			</div>
			<div class="span4">
  			<div class="center2">
    			<%= a.label :city %>
    			<%= a.text_field :city %>
  			</div>
			</div>

			<div class="span4">
  			<div class="left">
					<div class="center2">
						<%= a.label :state %>
    				<%= a.text_field :state %>
  				</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="span4">
				<div class="right">
					<div class="center2">
						<%= a.label :zip %>
    				<%= a.text_field :zip %>
  				</div>
				</div>
			</div>
			<div class="span4">
  			<div class="center2">
					<%= a.label :cell %>
    			<%= a.telephone_field :cell %>
  			</div>
			</div>
			<div class="span4">
  			<div class="left">
					<div class="center2">
						<%= a.label :email %>
    				<%= a.email_field :email %>
  				</div>
				</div>
			</div>
		</div>	
	<% end %>

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :street2 %><br />
    <%= f.text_field :street2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :cell %><br />
    <%= f.text_field :cell %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Street</th>
    <th>Street2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Cell</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.street %></td>
    <td><%= address.street2 %></td>
    <td><%= address.city %></td>
    <td><%= address.state %></td>
    <td><%= address.zip %></td>
    <td><%= address.cell %></td>
    <td><%= address.email %></td>
    <td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Street:</b>
  <%= @address.street %>
</p>

<p>
  <b>Street2:</b>
  <%= @address.street2 %>
</p>

<p>
  <b>City:</b>
  <%= @address.city %>
</p>

<p>
  <b>State:</b>
  <%= @address.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @address.zip %>
</p>

<p>
  <b>Cell:</b>
  <%= @address.cell %>
</p>

<p>
  <b>Email:</b>
  <%= @address.email %>
</p>


<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>