config/routes.rb
Rsvp::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"} 

	devise_scope :user do
  	match "/registrations/list_invites" => "registrations#list"
  	match "/registrations/logon" => "registrations#create"
	end
  devise_for :admins

  resources :addresses

  resources :invitations

	match '/invitations/send_save_the_date', :to => 'invitations#send_save_the_date', :as => 'send_save_the_date'
	match '/registrations/list_invites', :to => 'registrations#list', :as => 'list_invites'
	match '/registrations/logon', :to => 'registrations#create', :as => 'login_to_invite'

	match '/registry', :to => 'home#registry', :as => 'registry'
	match '/itinerary', :to => 'home#itinerary', :as => 'itinerary'
	match '/accommodations', :to => 'home#accommodations', :as => 'accommodations'
	match '/venue', :to => 'home#venue', :as => 'venue'

	match '/dashboard', :to => 'dashboard#main', :as => 'dashboard'
	match '/admin_index', :to => 'invitations#admin_index', :as => 'admin_index'
	match '/thankyou', :to => 'invitations#thankyou', :as => 'thankyou'
	match '/thankyou_gift', :to => 'home#thankyou'

  root :to => "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rsvp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
		<!--link href='http://fonts.googleapis.com/css?family=Petit+Formal+Script' rel='stylesheet' type='text/css'-->

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>

  <body class="kickass" >
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          	<button type="button" class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
          	</button>
          	<a class="brand nav_bottom" href="<%= root_path() %>">brooke & doug's wedding</a>
          	<div class="container nav-collapse">
            	<ul class="nav pull-right nav_center">
              	<li id="rsvp"><%= link_to "rsvp", invitations_path() %></li>
								<li class="divider-vertical"></li>
								<li id="rsvp"><%= link_to "events", itinerary_path() %></li>
								<li class="divider-vertical"></li>
              	<li id="venue"><%= link_to "venue", venue_path() %></li>
								<li class="divider-vertical"></li>
              	<li id="accommodations"><%= link_to "accommodations", accommodations_path()  %></li>
								<li class="divider-vertical"></li>
              	<li id="registry"><%= link_to "registry", registry_path() %></li>
            	</ul>
          	</div>
        	</div>
      	</div>
    	</div>
		</div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
					 		<div class="container">
              	<%= yield %>
							</div>
            </div>
        	</div--><!--/span-->
        </div><!--/row-->
      </div><!--/content-->
    </div> <!-- /container -->
  </body>
</html>